// depth of field test
// 3 spheres and light over cube using lens on camera

// generate checkered cube
translate 0 -2.5 0
scale 10 1 10
material 1 0 0  .2 .8 0 1   0 0 1   1
cube

// red sphere
initTM
translate -3 0 0
material 1 0 0 .2 .6 .8 50
sphere

// yellow sphere
initTM
material 1 1 0 .2 .6 .8 50
sphere

// green dsphere
initTM
translate 3 0 0
material 0 1 0 .2 .6 .8 50
sphere

light 50 100 0 10000

camera 5 0 2  0 0 0
perspective 2 1 1
lens 5.5 0.1

trace 512 256 PIC9.tiff 8
quit
